[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["ucwong <ucwong@126.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.2"

[build-dependencies]
cc = "1.0"
